### ISSUE TITLE
Strange head and body position

### ISSUE THREAD

**Issue by Danifoxe** [arboriginal/Chair#2]
**Describe the bug**
body doesnt look aligned to chair when move camera. Sitting only working good when facing to south.

**To Reproduce**
Only sit in some stair and change camera to third person.

**Expected behavior**
body must be aligned to the chair like in a boat when you move camera.

**Screenshots**
![2020-01-11_22 36 53](https://user-images.githubusercontent.com/59784220/72213790-1c858180-34c3-11ea-98a6-41ac9008f021.png)
![2020-01-11_22 37 15](https://user-images.githubusercontent.com/59784220/72213793-27d8ad00-34c3-11ea-8957-d83535743804.png)

**Environment**
 - Java version: 1.15.1
 - Paper version: 1.15.1 ( 41)
 - Plugin version 1.2

**Comment by arboriginal** [comment]
The plugin makes the player mount an invisible vehicle, the plugin doesn't manage by itself how head and body are positioned but re-use Minecraft behavior.

I suppose it could be modified by constantly checking and modifying the player position, but it will have impacts on the server performances: The player position event is called very very often (maybe 50 times per second, for each connected player).

So, as mentioned on the plugin page, I prefer to keep the plugin light instead of trying to deal with details. You can see in the attached picture you will have the same result on some other vehicles:

![2020-01-12_05 10 50](https://user-images.githubusercontent.com/1117167/72214040-473efc80-34fa-11ea-8d3f-ea9ca61198dd.png)
![2020-01-12_05 11 42](https://user-images.githubusercontent.com/1117167/72214041-473efc80-34fa-11ea-84b5-d71cd1e667f5.png)
