### ISSUE TITLE
[1.2] GriefPrevention bug (due to TeleportCause.ENDER_PEARL)

### ISSUE THREAD

**Issue by CookLoco** [arboriginal/Chair#3]
If players in a claim (from another player) use chairs they will receive 1 ender pearl each time, this is due that the teleport cause used in this plugin is "ENDER_PEARL" and GriefPrevention check that reason, cancel the event and give to the player the ender pearl "used"

**Comment by arboriginal** [comment]
Thanks for the report. How I missed that??? (I'm also using GriefPrevention)

I used the _ENDER_PEARL_ reason to be sure plugins like essentials don't register the location for `/back` command, but after verifying the [source code](https://github.com/EssentialsX/Essentials/blob/32ef61197f9748ac308b444f3b70029b87d2fdd3/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L421), it only do it for reasons _PLUGIN_ (default) or _COMMAND_.

Will be fixed in next version, released in a few minutes.
